spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: postExchange
  mail:
    host: smtp.gmail.com
    port: 465
    username: durcit4@gmail.com
    password: gssghdohyuurxmfc
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
    protocol: smtp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/durcit
    username: practice1
    password: practice1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

        registration:
          google:
            client-id: 559095591861-7bjf0m9hf2n896pe48o7e9kkgqu3n0mv.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-name: Naver
            client-id: 8aUvEJTKmgPlHkuUGG6e
            client-secret: 6fvwS1jfZo
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - name
              - email
          kakao:
            client-name: Kakao
            client-id: 29e3d319e2b348999fddcde6b9ff9a09
            client-secret: HvHb8runrvKQyWYNcfjKeoq2IrHoha7e
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname

cloud:
  aws:
    credentials:
      access-key: AKIAR7HWYAB2MV5IGNMY
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

custom:
  s3:
    max-file-size: 10485760 #10MB
    presigned-url:
      expiration-time: 30
    bucket-name: burcit
  email:
    verification-url: http://localhost:8080/auth/verify?token=
  jwt:
    redirection:
      base-url: http://localhost:3000/auth
    validation:
      access: 600000
      refresh: 8640000
    secret:
      app-key: 878DF3DCBA23348529484E5B871BEB5EFEEA295441343CDDEE52E95F8942F2E9
      origin-key: 39fb3bb2-0500-40aa-be70-e2c75050eab9